<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class CriarEsportesCategoriasCotacao extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('esportes_categorias_cotacao', function (Blueprint $table) {
            $table->bigIncrements('id');

            $table->string('mercado');
            $table->string('mercado_descricao');

            $table->string('palpite');
            $table->string('palpite_descricao');

            $table->string('esporte')->default('futebol');

            $table->boolean('ativo')->default(true);

            $table->tinyInteger('alterar_cotacao')->default(0);
        });

        \Illuminate\Support\Facades\DB::table('esportes_categorias_cotacao')->insert([
            [
                'palpite' => 'even',
                'mercado' => '1st_half_goals_odd_even',
                'mercado_descricao' => '1º tempo - Total de gols par ou ímpar',
                'palpite_descricao' => 'Total de gols par - 1º tempo',
            ],
            [
                'palpite' => 'odd',
                'mercado' => '1st_half_goals_odd_even',
                'mercado_descricao' => '1º tempo - Total de gols par ou ímpar',
                'palpite_descricao' => 'Total de gols ímpar - 1º tempo',
            ],
            [
                'palpite' => 'over 1',
                'mercado' => '2nd_half_goals',
                'mercado_descricao' => '2º tempo - Gols Mais/Menos',
                'palpite_descricao' => '1 ou mais gols - 2º tempo',
            ],
            [
                'palpite' => 'over 2',
                'mercado' => '2nd_half_goals',
                'mercado_descricao' => '2º tempo - Gols Mais/Menos',
                'palpite_descricao' => '2 ou mais gols - 2º tempo',
            ],
            [
                'palpite' => 'over 3',
                'mercado' => '2nd_half_goals',
                'mercado_descricao' => '2º tempo - Gols Mais/Menos',
                'palpite_descricao' => '3 ou mais gols - 2º tempo',
            ],
            [
                'palpite' => 'over 4',
                'mercado' => '2nd_half_goals',
                'mercado_descricao' => '2º tempo - Gols Mais/Menos',
                'palpite_descricao' => '4 ou mais gols - 2º tempo',
            ],
            [
                'palpite' => 'under 0',
                'mercado' => '2nd_half_goals',
                'mercado_descricao' => '2º tempo - Gols Mais/Menos',
                'palpite_descricao' => 'Nenhum gol - 2º tempo',
            ],
            [
                'palpite' => 'under 1',
                'mercado' => '2nd_half_goals',
                'mercado_descricao' => '2º tempo - Gols Mais/Menos',
                'palpite_descricao' => '1 ou menos gols - 2º tempo',
            ],
            [
                'palpite' => 'under 2',
                'mercado' => '2nd_half_goals',
                'mercado_descricao' => '2º tempo - Gols Mais/Menos',
                'palpite_descricao' => '2 ou menos gols - 2º tempo',
            ],
            [
                'palpite' => 'under 3',
                'mercado' => '2nd_half_goals',
                'mercado_descricao' => '2º tempo - Gols Mais/Menos',
                'palpite_descricao' => '3 ou menos gols - 2º tempo',
            ],
            [
                'palpite' => 'even',
                'mercado' => '2nd_half_goals_odd_even',
                'mercado_descricao' => '2º tempo - Total de gols par ou ímpar',
                'palpite_descricao' => 'Total de gols par - 2º tempo',
            ],
            [
                'palpite' => 'odd',
                'mercado' => '2nd_half_goals_odd_even',
                'mercado_descricao' => '2º tempo - Total de gols par ou ímpar',
                'palpite_descricao' => 'Total de gols ímpar - 2º tempo',
            ],
            [
                'palpite' => '1',
                'mercado' => '2nd_half_result',
                'mercado_descricao' => '2º tempo - Vencedor',
                'palpite_descricao' => 'Casa - 2º tempo',
            ],
            [
                'palpite' => '2',
                'mercado' => '2nd_half_result',
                'mercado_descricao' => '2º tempo - Vencedor',
                'palpite_descricao' => 'Fora - 2º tempo',
            ],
            [
                'palpite' => 'X',
                'mercado' => '2nd_half_result',
                'mercado_descricao' => '2º tempo - Vencedor',
                'palpite_descricao' => 'Empate - 2º tempo',
            ],
            [
                'palpite' => '0',
                'mercado' => 'away-team-exact-goals',
                'mercado_descricao' => 'Fora - Quantidade exata de gols',
                'palpite_descricao' => 'Fora: 0 gols',
            ],
            [
                'palpite' => '1',
                'mercado' => 'away-team-exact-goals',
                'mercado_descricao' => 'Fora - Quantidade exata de gols',
                'palpite_descricao' => 'Fora: 1 gol',
            ],
            [
                'palpite' => '2',
                'mercado' => 'away-team-exact-goals',
                'mercado_descricao' => 'Fora - Quantidade exata de gols',
                'palpite_descricao' => 'Fora: 2 gol(s)',
            ],
            [
                'palpite' => '3+',
                'mercado' => 'away-team-exact-goals',
                'mercado_descricao' => 'Fora - Quantidade exata de gols',
                'palpite_descricao' => 'Fora: 3+ gol(s)',
            ],
            [
                'palpite' => 'even',
                'mercado' => 'away-team-odd-even-goals',
                'mercado_descricao' => 'Fora - Par ou Ímpar',
                'palpite_descricao' => 'Fora - Total de gols par',
            ],
            [
                'palpite' => 'odd',
                'mercado' => 'away-team-odd-even-goals',
                'mercado_descricao' => 'Fora - Par ou Ímpar',
                'palpite_descricao' => 'Fora - Total de gols ímpar',
            ],
            [
                'palpite' => 'no',
                'mercado' => 'both_teams_to_score',
                'mercado_descricao' => 'Ambas marcam',
                'palpite_descricao' => 'Apenas uma marca',
            ],
            [
                'palpite' => 'yes',
                'mercado' => 'both_teams_to_score',
                'mercado_descricao' => 'Ambas marcam',
                'palpite_descricao' => 'Ambas marcam',
            ],
            [
                'palpite' => 'no',
                'mercado' => 'both_teams_to_score_in_1st_half',
                'mercado_descricao' => '1º tempo - Ambas marcam',
                'palpite_descricao' => 'Apenas uma marca - 1º tempo',
            ],
            [
                'palpite' => 'yes',
                'mercado' => 'both_teams_to_score_in_1st_half',
                'mercado_descricao' => '1º tempo - Ambas marcam',
                'palpite_descricao' => 'Ambas marcam - 1º tempo',
            ],
            [
                'palpite' => 'no',
                'mercado' => 'both_teams_to_score_in_2nd_half',
                'mercado_descricao' => '2º tempo - Ambas marcam',
                'palpite_descricao' => 'Apenas uma marca - 2º tempo',
            ],
            [
                'palpite' => 'yes',
                'mercado' => 'both_teams_to_score_in_2nd_half',
                'mercado_descricao' => '2º tempo - Ambas marcam',
                'palpite_descricao' => 'Ambas marcam - 2º tempo',
            ],
            [
                'palpite' => '0-0',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 0-0',
            ],
            [
                'palpite' => '0-1',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 0-1',
            ],
            [
                'palpite' => '0-10',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 0-10',
            ],
            [
                'palpite' => '0-11',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 0-11',
            ],
            [
                'palpite' => '0-2',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 0-2',
            ],
            [
                'palpite' => '0-3',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 0-3',
            ],
            [
                'palpite' => '0-4',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 0-4',
            ],
            [
                'palpite' => '0-5',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 0-5',
            ],
            [
                'palpite' => '0-6',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 0-6',
            ],
            [
                'palpite' => '0-7',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 0-7',
            ],
            [
                'palpite' => '0-8',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 0-8',
            ],
            [
                'palpite' => '0-9',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 0-9',
            ],
            [
                'palpite' => '1-0',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 1-0',
            ],
            [
                'palpite' => '1-1',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 1-1',
            ],
            [
                'palpite' => '1-10',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 1-10',
            ],
            [
                'palpite' => '1-11',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 1-11',
            ],
            [
                'palpite' => '1-2',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 1-2',
            ],
            [
                'palpite' => '1-3',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 1-3',
            ],
            [
                'palpite' => '1-4',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 1-4',
            ],
            [
                'palpite' => '1-5',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 1-5',
            ],
            [
                'palpite' => '1-6',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 1-6',
            ],
            [
                'palpite' => '1-7',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 1-7',
            ],
            [
                'palpite' => '1-8',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 1-8',
            ],
            [
                'palpite' => '1-9',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 1-9',
            ],
            [
                'palpite' => '10-0',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 10-0',
            ],
            [
                'palpite' => '10-1',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 10-1',
            ],
            [
                'palpite' => '10-2',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 10-2',
            ],
            [
                'palpite' => '11-0',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 11-0',
            ],
            [
                'palpite' => '11-1',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 11-1',
            ],
            [
                'palpite' => '12-0',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 12-0',
            ],
            [
                'palpite' => '12-1',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 12-1',
            ],
            [
                'palpite' => '13-0',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 13-0',
            ],
            [
                'palpite' => '13-1',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 13-1',
            ],
            [
                'palpite' => '14-0',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 14-0',
            ],
            [
                'palpite' => '2-0',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 2-0',
            ],
            [
                'palpite' => '2-1',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 2-1',
            ],
            [
                'palpite' => '2-10',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 2-10',
            ],
            [
                'palpite' => '2-2',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 2-2',
            ],
            [
                'palpite' => '2-3',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 2-3',
            ],
            [
                'palpite' => '2-4',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 2-4',
            ],
            [
                'palpite' => '2-5',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 2-5',
            ],
            [
                'palpite' => '2-6',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 2-6',
            ],
            [
                'palpite' => '2-7',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 2-7',
            ],
            [
                'palpite' => '2-8',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 2-8',
            ],
            [
                'palpite' => '2-9',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 2-9',
            ],
            [
                'palpite' => '3-0',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 3-0',
            ],
            [
                'palpite' => '3-1',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 3-1',
            ],
            [
                'palpite' => '3-2',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 3-2',
            ],
            [
                'palpite' => '3-3',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 3-3',
            ],
            [
                'palpite' => '3-4',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 3-4',
            ],
            [
                'palpite' => '3-5',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 3-5',
            ],
            [
                'palpite' => '3-6',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 3-6',
            ],
            [
                'palpite' => '3-7',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 3-7',
            ],
            [
                'palpite' => '4-0',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 4-0',
            ],
            [
                'palpite' => '4-1',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 4-1',
            ],
            [
                'palpite' => '4-2',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 4-2',
            ],
            [
                'palpite' => '4-3',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 4-3',
            ],
            [
                'palpite' => '4-4',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 4-4',
            ],
            [
                'palpite' => '4-5',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 4-5',
            ],
            [
                'palpite' => '5-0',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 5-0',
            ],
            [
                'palpite' => '5-1',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 5-1',
            ],
            [
                'palpite' => '5-2',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 5-2',
            ],
            [
                'palpite' => '5-3',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 5-3',
            ],
            [
                'palpite' => '5-4',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 5-4',
            ],
            [
                'palpite' => '5-5',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 5-5',
            ],
            [
                'palpite' => '6-0',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 6-0',
            ],
            [
                'palpite' => '6-1',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 6-1',
            ],
            [
                'palpite' => '6-2',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 6-2',
            ],
            [
                'palpite' => '6-3',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 6-3',
            ],
            [
                'palpite' => '6-4',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 6-4',
            ],
            [
                'palpite' => '7-0',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 7-0',
            ],
            [
                'palpite' => '7-1',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 7-1',
            ],
            [
                'palpite' => '7-2',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 7-2',
            ],
            [
                'palpite' => '7-3',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 7-3',
            ],
            [
                'palpite' => '8-0',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 8-0',
            ],
            [
                'palpite' => '8-1',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 8-1',
            ],
            [
                'palpite' => '8-2',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 8-2',
            ],
            [
                'palpite' => '9-0',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 9-0',
            ],
            [
                'palpite' => '9-1',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 9-1',
            ],
            [
                'palpite' => '9-2',
                'mercado' => 'correct_score',
                'mercado_descricao' => 'Placar exato',
                'palpite_descricao' => 'Placar 9-2',
            ],
            [
                'palpite' => '12',
                'mercado' => 'double_chance',
                'mercado_descricao' => 'Dupla chance',
                'palpite_descricao' => 'Casa ou Fora',
            ],
            [
                'palpite' => '1X',
                'mercado' => 'double_chance',
                'mercado_descricao' => 'Dupla chance',
                'palpite_descricao' => 'Casa ou Empate',
            ],
            [
                'palpite' => 'X2',
                'mercado' => 'double_chance',
                'mercado_descricao' => 'Dupla chance',
                'palpite_descricao' => 'Fora ou Empate',
            ],
            [
                'palpite' => '1',
                'mercado' => 'exact_total_goals',
                'mercado_descricao' => 'Total exato de gols',
                'palpite_descricao' => 'Total de 1 gol',
            ],
            [
                'palpite' => '2',
                'mercado' => 'exact_total_goals',
                'mercado_descricao' => 'Total exato de gols',
                'palpite_descricao' => 'Total de 2 gols',
            ],
            [
                'palpite' => '3',
                'mercado' => 'exact_total_goals',
                'mercado_descricao' => 'Total exato de gols',
                'palpite_descricao' => 'Total de 3 gols',
            ],
            [
                'palpite' => '4',
                'mercado' => 'exact_total_goals',
                'mercado_descricao' => 'Total exato de gols',
                'palpite_descricao' => 'Total de 4 gols',
            ],
            [
                'palpite' => '5',
                'mercado' => 'exact_total_goals',
                'mercado_descricao' => 'Total exato de gols',
                'palpite_descricao' => 'Total de 5 gols',
            ],
            [
                'palpite' => '6',
                'mercado' => 'exact_total_goals',
                'mercado_descricao' => 'Total exato de gols',
                'palpite_descricao' => 'Total de 6 gols',
            ],
            [
                'palpite' => '7+',
                'mercado' => 'exact_total_goals',
                'mercado_descricao' => 'Total exato de gols',
                'palpite_descricao' => 'Total de +7 gols',
            ],
            [
                'palpite' => 'over 1',
                'mercado' => 'first_half_goals',
                'mercado_descricao' => '1º tempo - Gols Mais/Menos',
                'palpite_descricao' => '1 ou mais gols - 1º tempo',
            ],
            [
                'palpite' => 'over 2',
                'mercado' => 'first_half_goals',
                'mercado_descricao' => '1º tempo - Gols Mais/Menos',
                'palpite_descricao' => '2 ou mais gols - 1º tempo',
            ],
            [
                'palpite' => 'over 3',
                'mercado' => 'first_half_goals',
                'mercado_descricao' => '1º tempo - Gols Mais/Menos',
                'palpite_descricao' => '3 ou mais gols - 1º tempo',
            ],
            [
                'palpite' => 'over 4',
                'mercado' => 'first_half_goals',
                'mercado_descricao' => '1º tempo - Gols Mais/Menos',
                'palpite_descricao' => '4 ou mais gols - 1º tempo',
            ],
            [
                'palpite' => 'under 0',
                'mercado' => 'first_half_goals',
                'mercado_descricao' => '1º tempo - Gols Mais/Menos',
                'palpite_descricao' => 'Nenhum gol - 1º tempo',
            ],
            [
                'palpite' => 'under 1',
                'mercado' => 'first_half_goals',
                'mercado_descricao' => '1º tempo - Gols Mais/Menos',
                'palpite_descricao' => '1 ou menos gols - 1º tempo',
            ],
            [
                'palpite' => 'under 2',
                'mercado' => 'first_half_goals',
                'mercado_descricao' => '1º tempo - Gols Mais/Menos',
                'palpite_descricao' => '2 ou menos gols - 1º tempo',
            ],
            [
                'palpite' => 'under 3',
                'mercado' => 'first_half_goals',
                'mercado_descricao' => '1º tempo - Gols Mais/Menos',
                'palpite_descricao' => '3 ou menos gols - 1º tempo',
            ],
            [
                'palpite' => '1',
                'mercado' => 'full_time_result',
                'mercado_descricao' => 'Vencedor da partida',
                'palpite_descricao' => 'Casa',
            ],
            [
                'palpite' => '2',
                'mercado' => 'full_time_result',
                'mercado_descricao' => 'Vencedor da partida',
                'palpite_descricao' => 'Fora',
            ],
            [
                'palpite' => 'X',
                'mercado' => 'full_time_result',
                'mercado_descricao' => 'Vencedor da partida',
                'palpite_descricao' => 'Empate',
            ],
            [
                'palpite' => 'even',
                'mercado' => 'goals_odd_even',
                'mercado_descricao' => 'Total de gols par ou ímpar',
                'palpite_descricao' => 'Total de gols par',
            ],
            [
                'palpite' => 'odd',
                'mercado' => 'goals_odd_even',
                'mercado_descricao' => 'Total de gols par ou ímpar',
                'palpite_descricao' => 'Total de gols ímpar',
            ],
            [
                'palpite' => 'over 1',
                'mercado' => 'goals_over_under',
                'mercado_descricao' => 'Gols Mais/Menos',
                'palpite_descricao' => '1 ou mais gols',
            ],
            [
                'palpite' => 'over 2',
                'mercado' => 'goals_over_under',
                'mercado_descricao' => 'Gols Mais/Menos',
                'palpite_descricao' => '2 ou mais gols',
            ],
            [
                'palpite' => 'over 3',
                'mercado' => 'goals_over_under',
                'mercado_descricao' => 'Gols Mais/Menos',
                'palpite_descricao' => '3 ou mais gols',
            ],
            [
                'palpite' => 'over 4',
                'mercado' => 'goals_over_under',
                'mercado_descricao' => 'Gols Mais/Menos',
                'palpite_descricao' => '4 ou mais gols',
            ],
            [
                'palpite' => 'under 0',
                'mercado' => 'goals_over_under',
                'mercado_descricao' => 'Gols Mais/Menos',
                'palpite_descricao' => 'Nenhum gol',
            ],
            [
                'palpite' => 'under 1',
                'mercado' => 'goals_over_under',
                'mercado_descricao' => 'Gols Mais/Menos',
                'palpite_descricao' => '1 ou menos gols',
            ],
            [
                'palpite' => 'under 2',
                'mercado' => 'goals_over_under',
                'mercado_descricao' => 'Gols Mais/Menos',
                'palpite_descricao' => '2 ou menos gols',
            ],
            [
                'palpite' => 'under 3',
                'mercado' => 'goals_over_under',
                'mercado_descricao' => 'Gols Mais/Menos',
                'palpite_descricao' => '3 ou menos gols',
            ],
            [
                'palpite' => '0-0',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 0-0 - 1º tempo',
            ],
            [
                'palpite' => '0-1',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 0-1 - 1º tempo',
            ],
            [
                'palpite' => '0-2',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 0-2 - 1º tempo',
            ],
            [
                'palpite' => '0-3',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 0-3 - 1º tempo',
            ],
            [
                'palpite' => '0-4',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 0-4 - 1º tempo',
            ],
            [
                'palpite' => '0-5',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 0-5 - 1º tempo',
            ],
            [
                'palpite' => '0-6',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 0-6 - 1º tempo',
            ],
            [
                'palpite' => '0-7',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 0-7 - 1º tempo',
            ],
            [
                'palpite' => '1-0',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 1-0 - 1º tempo',
            ],
            [
                'palpite' => '1-1',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 1-1 - 1º tempo',
            ],
            [
                'palpite' => '1-2',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 1-2 - 1º tempo',
            ],
            [
                'palpite' => '1-3',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 1-3 - 1º tempo',
            ],
            [
                'palpite' => '1-4',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 1-4 - 1º tempo',
            ],
            [
                'palpite' => '1-5',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 1-5 - 1º tempo',
            ],
            [
                'palpite' => '1-6',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 1-6 - 1º tempo',
            ],
            [
                'palpite' => '2-0',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 2-0 - 1º tempo',
            ],
            [
                'palpite' => '2-1',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 2-1 - 1º tempo',
            ],
            [
                'palpite' => '2-2',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 2-2 - 1º tempo',
            ],
            [
                'palpite' => '2-3',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 2-3 - 1º tempo',
            ],
            [
                'palpite' => '2-4',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 2-4 - 1º tempo',
            ],
            [
                'palpite' => '3-0',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 3-0 - 1º tempo',
            ],
            [
                'palpite' => '3-1',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 3-1 - 1º tempo',
            ],
            [
                'palpite' => '3-2',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 3-2 - 1º tempo',
            ],
            [
                'palpite' => '3-3',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 3-3 - 1º tempo',
            ],
            [
                'palpite' => '4-0',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 4-0 - 1º tempo',
            ],
            [
                'palpite' => '4-1',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 4-1 - 1º tempo',
            ],
            [
                'palpite' => '4-2',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 4-2 - 1º tempo',
            ],
            [
                'palpite' => '5-0',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 5-0 - 1º tempo',
            ],
            [
                'palpite' => '5-1',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 5-1 - 1º tempo',
            ],
            [
                'palpite' => '5-2',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 5-2 - 1º tempo',
            ],
            [
                'palpite' => '6-0',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 6-0 - 1º tempo',
            ],
            [
                'palpite' => '6-1',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 6-1 - 1º tempo',
            ],
            [
                'palpite' => '7-0',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 7-0 - 1º tempo',
            ],
            [
                'palpite' => '8-0',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 8-0 - 1º tempo',
            ],
            [
                'palpite' => '9-0',
                'mercado' => 'half_time_correct_score',
                'mercado_descricao' => '1º tempo - Placar exato',
                'palpite_descricao' => 'Placar 9-0 - 1º tempo',
            ],
            [
                'palpite' => '12',
                'mercado' => 'half_time_double_chance',
                'mercado_descricao' => '1º tempo - Dupla chance',
                'palpite_descricao' => 'Casa ou Fora - 1º tempo',
            ],
            [
                'palpite' => '1X',
                'mercado' => 'half_time_double_chance',
                'mercado_descricao' => '1º tempo - Dupla chance',
                'palpite_descricao' => 'Casa ou Empate - 1º tempo',
            ],
            [
                'palpite' => 'X2',
                'mercado' => 'half_time_double_chance',
                'mercado_descricao' => '1º tempo - Dupla chance',
                'palpite_descricao' => 'Fora ou Empate - 1º tempo',
            ],
            [
                'palpite' => '1 - 1',
                'mercado' => 'half_time_full_time',
                'mercado_descricao' => 'Vencedor ao intervalo e vencedor ao final do jogo',
                'palpite_descricao' => 'Casa (1º tempo) / Casa (partida)',
            ],
            [
                'palpite' => '1 - 2',
                'mercado' => 'half_time_full_time',
                'mercado_descricao' => 'Vencedor ao intervalo e vencedor ao final do jogo',
                'palpite_descricao' => 'Casa (1º tempo) / Fora (partida)',
            ],
            [
                'palpite' => '1 - X',
                'mercado' => 'half_time_full_time',
                'mercado_descricao' => 'Vencedor ao intervalo e vencedor ao final do jogo',
                'palpite_descricao' => 'Casa (1º tempo) / Empate (partida)',
            ],
            [
                'palpite' => '2 - 1',
                'mercado' => 'half_time_full_time',
                'mercado_descricao' => 'Vencedor ao intervalo e vencedor ao final do jogo',
                'palpite_descricao' => 'Fora (1º tempo) / Casa (partida)',
            ],
            [
                'palpite' => '2 - 2',
                'mercado' => 'half_time_full_time',
                'mercado_descricao' => 'Vencedor ao intervalo e vencedor ao final do jogo',
                'palpite_descricao' => 'Fora (1º tempo) / Fora (partida)',
            ],
            [
                'palpite' => '2 - X',
                'mercado' => 'half_time_full_time',
                'mercado_descricao' => 'Vencedor ao intervalo e vencedor ao final do jogo',
                'palpite_descricao' => 'Fora (1º tempo) / Empate (partida)',
            ],
            [
                'palpite' => 'X - 1',
                'mercado' => 'half_time_full_time',
                'mercado_descricao' => 'Vencedor ao intervalo e vencedor ao final do jogo',
                'palpite_descricao' => 'Empate (1º tempo) / Casa (partida)',
            ],
            [
                'palpite' => 'X - 2',
                'mercado' => 'half_time_full_time',
                'mercado_descricao' => 'Vencedor ao intervalo e vencedor ao final do jogo',
                'palpite_descricao' => 'Empate (1º tempo) / Fora (partida)',
            ],
            [
                'palpite' => 'X - X',
                'mercado' => 'half_time_full_time',
                'mercado_descricao' => 'Vencedor ao intervalo e vencedor ao final do jogo',
                'palpite_descricao' => 'Empate (1º tempo) / Empate (partida)',
            ],
            [
                'palpite' => '1',
                'mercado' => 'half_time_result',
                'mercado_descricao' => '1º tempo - Vencedor',
                'palpite_descricao' => 'Casa - 1º tempo',
            ],
            [
                'palpite' => '2',
                'mercado' => 'half_time_result',
                'mercado_descricao' => '1º tempo - Vencedor',
                'palpite_descricao' => 'Fora - 1º tempo',
            ],
            [
                'palpite' => 'X',
                'mercado' => 'half_time_result',
                'mercado_descricao' => '1º tempo - Vencedor',
                'palpite_descricao' => 'Empate - 1º tempo',
            ],
            [
                'palpite' => '1',
                'mercado' => 'half_with_most_goals',
                'mercado_descricao' => 'Tempo com mais gols',
                'palpite_descricao' => '1º tempo com mais gols',
            ],
            [
                'palpite' => '2',
                'mercado' => 'half_with_most_goals',
                'mercado_descricao' => 'Tempo com mais gols',
                'palpite_descricao' => '2º tempo com mais gols',
            ],
            [
                'palpite' => 'X',
                'mercado' => 'half_with_most_goals',
                'mercado_descricao' => 'Tempo com mais gols',
                'palpite_descricao' => 'Empate - sem tempo com mais gols',
            ],
            [
                'palpite' => 'away -1.5',
                'mercado' => 'handicap',
                'mercado_descricao' => 'Handicap',
                'palpite_descricao' => 'Fora -1.5',
            ],
            [
                'palpite' => 'home -1.5',
                'mercado' => 'handicap',
                'mercado_descricao' => 'Handicap',
                'palpite_descricao' => 'Casa -1.5',
            ],
            [
                'palpite' => '0',
                'mercado' => 'home-team-exact-goals',
                'mercado_descricao' => 'Casa - Quantidade exata de gols',
                'palpite_descricao' => 'Casa: 0 gols',
            ],
            [
                'palpite' => '1',
                'mercado' => 'home-team-exact-goals',
                'mercado_descricao' => 'Casa - Quantidade exata de gols',
                'palpite_descricao' => 'Casa: 1 gol',
            ],
            [
                'palpite' => '2',
                'mercado' => 'home-team-exact-goals',
                'mercado_descricao' => 'Casa - Quantidade exata de gols',
                'palpite_descricao' => 'Casa: 2 gols',
            ],
            [
                'palpite' => '3+',
                'mercado' => 'home-team-exact-goals',
                'mercado_descricao' => 'Casa - Quantidade exata de gols',
                'palpite_descricao' => 'Casa: 3+ gols',
            ],
            [
                'palpite' => 'even',
                'mercado' => 'home-team-odd-even-goals',
                'mercado_descricao' => 'Casa - Par ou Ímpar',
                'palpite_descricao' => 'Casa - Total de gols par',
            ],
            [
                'palpite' => 'odd',
                'mercado' => 'home-team-odd-even-goals',
                'mercado_descricao' => 'Casa - Par ou Ímpar',
                'palpite_descricao' => 'Casa - Total de gols ímpar',
            ],
            [
                'palpite' => '1 & no',
                'mercado' => 'result_both_teams_to_score',
                'mercado_descricao' => 'Vencedor / Ambas marcam',
                'palpite_descricao' => 'Casa ganha e fora não marca',
            ],
            [
                'palpite' => '1 & yes',
                'mercado' => 'result_both_teams_to_score',
                'mercado_descricao' => 'Vencedor / Ambas marcam',
                'palpite_descricao' => 'Casa ganha e ambas marcam',
            ],
            [
                'palpite' => '2 & no',
                'mercado' => 'result_both_teams_to_score',
                'mercado_descricao' => 'Vencedor / Ambas marcam',
                'palpite_descricao' => 'Fora ganha e casa não marca',
            ],
            [
                'palpite' => '2 & yes',
                'mercado' => 'result_both_teams_to_score',
                'mercado_descricao' => 'Vencedor / Ambas marcam',
                'palpite_descricao' => 'Fora ganha e ambas marcam',
            ],
            [
                'palpite' => 'X & no',
                'mercado' => 'result_both_teams_to_score',
                'mercado_descricao' => 'Vencedor / Ambas marcam',
                'palpite_descricao' => 'Empate e nenhuma equipe marca',
            ],
            [
                'palpite' => 'X & yes',
                'mercado' => 'result_both_teams_to_score',
                'mercado_descricao' => 'Vencedor / Ambas marcam',
                'palpite_descricao' => 'Empate e ambas marcam',
            ],
            [
                'palpite' => '1',
                'mercado' => 'teams-to-score',
                'mercado_descricao' => 'Equipes que marcam',
                'palpite_descricao' => 'Apenas casa marca',
            ],
            [
                'palpite' => '2',
                'mercado' => 'teams-to-score',
                'mercado_descricao' => 'Equipes que marcam',
                'palpite_descricao' => 'Apenas fora marca',
            ],
            [
                'palpite' => 'both',
                'mercado' => 'teams-to-score',
                'mercado_descricao' => 'Equipes que marcam',
                'palpite_descricao' => 'Ambas marcam',
            ],
            [
                'palpite' => 'no-goal',
                'mercado' => 'teams-to-score',
                'mercado_descricao' => 'Equipes que marcam',
                'palpite_descricao' => 'Apenas uma marca',
            ],
        ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('esportes_categorias_cotacao');
    }
}
